import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@styles/globals.css'
import { AppParams, Locale } from '@types'
import { i18n } from '@constants'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const generateStaticParams = (): AppParams[] =>
  i18n.locales.map(locale => ({ locale }))

type RootLayoutProps = {
  children: React.ReactNode,
  params?: AppParams
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const locale: Locale = params?.locale || 'fr'

  return (
    <html lang={locale}>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
